In [1]:
import numpy as np

In [2]:
list(range(5))

[0, 1, 2, 3, 4]

In [3]:
list( range(0,10) )

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list( range(0.4, 10.4) )

TypeError: ignored

The above code gives error. Hence, the solution is, using np.arange()

In [5]:
np.arange(.4, 10.)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [6]:
np.arange(.4, .10)

array([], dtype=float64)

In [7]:
np.arange(.4, 10.1 , 0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. ])

In [8]:
list( np.arange(.4, 10.1 , 0.2) )

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004]

In [9]:
np.linspace(1,5 , 20)   # Generate 20 data items which are in the range (1 to 5)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [10]:
np.logspace(1,5 , 10) # Generate log value of 20 data items which are in the range (1 to 5)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [11]:
#You can also give a log base to above function

np.logspace(1,5 , 10 , base = 2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))   # 3 rows and 4 columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.zeros((3,4,2))   # It will generate three 4 X 2 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
np.zeros((5,3,2)) # FIVE 3 X 2 matrices

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [16]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.ones((3, 3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
arr = np.ones(( 3,4 ))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [21]:
arr * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [22]:
(arr + 5)*4

array([[24., 24., 24., 24.],
       [24., 24., 24., 24.],
       [24., 24., 24., 24.]])

In [23]:
# Identity Matrices  -> Produces square matrix for one parameter

np.eye(4)    # 4 X 4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.eye(2,3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [25]:
arr1 = np.eye(5)

In [26]:
import pandas as pd

pd.DataFrame(arr1)

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

Hence, we can convert any array into a column

In [27]:
np.random.rand(2,3)   # Generates a 2-dim array like matrix with 2 rows and 3 columns

array([[0.59998509, 0.64013072, 0.73881534],
       [0.36453099, 0.23648759, 0.35008757]])

In [28]:
np.random.randn(2,3)

array([[ 0.15552608, -0.90249567,  1.81251438],
       [-0.98521192,  0.13246794,  1.10479947]])

np.random.rand() generates random data. Hence, its mean and std dev can be anything

np.random.rand() generates standard normal distribution data. Hence, its mean will be zero and std dev will be 1

In [29]:
np.random.randint(1,5  , (3,4))   # Generates 3 X 4 matrix array and data between (1 to 5)

array([[1, 2, 2, 3],
       [3, 3, 2, 3],
       [2, 2, 3, 4]])

In [30]:
arr2 = np.random.randint(1,5  , (3,4))
arr2.size

12

In [31]:
arr2.shape

(3, 4)

In [32]:
arr2.reshape(5,6)

ValueError: ignored

If you want to reshape, you must provide numbers which have same multipliers as previous shape.

Here, previous shape was (3,4)  -> 12

Hence. we can give(2,6) or (1,12)

In [33]:
arr2.reshape(1,12 )

array([[1, 4, 4, 3, 4, 2, 3, 4, 1, 3, 3, 1]])

In [34]:
arr2   # Changes are not saved. You can do reassignment to save changes

array([[1, 4, 4, 3],
       [4, 2, 3, 4],
       [1, 3, 3, 1]])

In [35]:
arr2.reshape(2,6)

array([[1, 4, 4, 3, 4, 2],
       [3, 4, 1, 3, 3, 1]])

In [36]:
arr2.reshape(6,2)

array([[1, 4],
       [4, 3],
       [4, 2],
       [3, 4],
       [1, 3],
       [3, 1]])

In [37]:
arr2.reshape(4,1)

ValueError: ignored

In [38]:
arr2.reshape(4,-1)

array([[1, 4, 4],
       [3, 4, 2],
       [3, 4, 1],
       [3, 3, 1]])

In [39]:
arr2.reshape(4,-3637377)

array([[1, 4, 4],
       [3, 4, 2],
       [3, 4, 1],
       [3, 3, 1]])

#### Hence, negative numbers have no impact

In [40]:
arr2.reshape(2,2,3)     # multiplier -> 12

array([[[1, 4, 4],
        [3, 4, 2]],

       [[3, 4, 1],
        [3, 3, 1]]])

In [41]:
arr1 = np.random.randint(1,10 , (5,6)) # data between 1 and 10. 5 row X 6 col
arr1

array([[3, 4, 8, 6, 5, 5],
       [1, 9, 4, 9, 1, 7],
       [5, 9, 1, 7, 4, 4],
       [8, 2, 9, 4, 2, 8],
       [3, 5, 4, 6, 6, 5]])

In [42]:
arr1>8

array([[False, False, False, False, False, False],
       [False,  True, False,  True, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False, False],
       [False, False, False, False, False, False]])

In [43]:
arr1[ arr1>8 ]

array([9, 9, 9, 9])

In [44]:
arr1[0]

array([3, 4, 8, 6, 5, 5])

In [45]:
arr1[0][0]

3

In [46]:
arr1[0,[0,1]]

array([3, 4])

In [47]:
arr1[2:4, 2:4]

array([[1, 7],
       [9, 4]])

In [48]:
arr1[2:4, [2,3]]

array([[1, 7],
       [9, 4]])

In [49]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [50]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [51]:
arr2

array([[1, 2, 1],
       [2, 1, 2],
       [1, 1, 2]])

In [52]:
arr1 + arr2

array([[2, 4, 2],
       [3, 2, 4],
       [2, 3, 3]])

In [53]:
arr1 - arr2

array([[ 0,  0,  0],
       [-1,  0,  0],
       [ 0,  1, -1]])

In [55]:
arr1 * arr2 # INDEXWISE MULTIPLICATION and NOT MATRIX STYLE MULTIPLICATION

array([[1, 4, 1],
       [2, 1, 4],
       [1, 2, 2]])

In [57]:
arr1 @ arr2   # Matrix Multiplicaton

array([[6, 5, 7],
       [5, 5, 7],
       [6, 5, 7]])

In [58]:
arr1 / arr2

array([[1. , 1. , 1. ],
       [0.5, 1. , 1. ],
       [1. , 2. , 0.5]])

In [59]:
arr1 // arr2

array([[1, 1, 1],
       [0, 1, 1],
       [1, 2, 0]])

In [60]:
arr1 / 0

<ipython-input-60-f39b50d43667>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [61]:
# Numpy -> Broadcasting

In [62]:
arr = np.zeros((3,4))

In [63]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [64]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

5 is added to each element of array. Hence, it is a broadcasting operation

In [65]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [66]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

1234 will be added to each row

In [78]:
b = np.array([[3,4,5]])

In [79]:
type(b)

numpy.ndarray

In [80]:
arr+b   # You need 4 numbers in b

ValueError: ignored

In [81]:
# OR you can rotate and broadcast

arr + b.T

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [82]:
b.T

array([[3],
       [4],
       [5]])

In [83]:
np.sqrt([1,2,3,4,5])

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [84]:
arr1

array([[1, 2, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [85]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.        ],
       [1.        , 1.        , 1.41421356],
       [1.        , 1.41421356, 1.        ]])

In [86]:
np.sqr(arr1)

AttributeError: ignored

In [87]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 2.71828183],
       [2.71828183, 2.71828183, 7.3890561 ],
       [2.71828183, 7.3890561 , 2.71828183]])

In [88]:
np.mean(arr1)

1.3333333333333333

In [89]:
np.min(arr1)

1

In [90]:
np.max(arr1)

2