In [1]:
import numpy as np

## Numpy - Array Manipulation

### randn generates numbers from a normal distribution with a mean of 0 and a standard deviation of 1, while `rand` generates numbers from a uniform distribution between 0 and 1.

In [2]:
arr = np.random.randint(1,18, (4,4))
arr

array([[ 8, 12,  4,  7],
       [ 4,  1,  3,  8],
       [ 8, 10,  1,  4],
       [13,  9,  4, 16]])

In [3]:
arr.reshape(8,2)

array([[ 8, 12],
       [ 4,  7],
       [ 4,  1],
       [ 3,  8],
       [ 8, 10],
       [ 1,  4],
       [13,  9],
       [ 4, 16]])

In [4]:
arr.reshape(2,8)

array([[ 8, 12,  4,  7,  4,  1,  3,  8],
       [ 8, 10,  1,  4, 13,  9,  4, 16]])

In [5]:
arr.T  # Transpose

array([[ 8,  4,  8, 13],
       [12,  1, 10,  9],
       [ 4,  3,  1,  4],
       [ 7,  8,  4, 16]])

In [6]:
arr.flatten()

array([ 8, 12,  4,  7,  4,  1,  3,  8,  8, 10,  1,  4, 13,  9,  4, 16])

In [7]:
np.expand_dims(arr)

TypeError: ignored

In [8]:
arr

array([[ 8, 12,  4,  7],
       [ 4,  1,  3,  8],
       [ 8, 10,  1,  4],
       [13,  9,  4, 16]])

In [9]:
np.expand_dims(arr, axis = 1)

array([[[ 8, 12,  4,  7]],

       [[ 4,  1,  3,  8]],

       [[ 8, 10,  1,  4]],

       [[13,  9,  4, 16]]])

In [10]:
np.expand_dims(arr, axis = 0)

array([[[ 8, 12,  4,  7],
        [ 4,  1,  3,  8],
        [ 8, 10,  1,  4],
        [13,  9,  4, 16]]])

In [11]:
np.expand_dims(arr, axis = 1).ndim

3

Hence, in this way, you can increase dimension of an array

In [12]:
data = np.array([[1], [2], [3]])

In [13]:
np.squeeze(data)    # reduces dimension

array([1, 2, 3])

In [14]:
np.repeat(data , 2)

array([1, 1, 2, 2, 3, 3])

In [15]:
np.repeat(data , 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [16]:
np.roll(data, 2)  # It rotates the dataset by 2 places

array([[2],
       [3],
       [1]])

In [17]:
np.roll(data, 1)

array([[3],
       [1],
       [2]])

In [18]:
np.diag(data)  # Extract a diagonal or construct a diagonal array

array([1])

In [19]:
np.diag( np.array([1,2,3,4]) )

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
np.diag( np.array([1,2,3]) )

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [21]:
np.diag( np.array([[1,2,3]]) )

array([1])

In [22]:
np.array([[1,2,3]]).ndim

2

In [23]:
np.array([1,2,3]).ndim

1

### Numpy -> Binary Operation

In [24]:
arr1 = np.random.randint(1,10, (3,4))
arr1

array([[6, 8, 4, 3],
       [2, 6, 5, 7],
       [6, 5, 8, 6]])

In [25]:
arr2 = np.random.randint(1,10, (3,4))
arr2

array([[2, 8, 2, 4],
       [8, 4, 5, 5],
       [8, 6, 1, 7]])

In [26]:
arr1 + arr2  # indexwise sum

array([[ 8, 16,  6,  7],
       [10, 10, 10, 12],
       [14, 11,  9, 13]])

In [27]:
arr1 * arr2

array([[12, 64,  8, 12],
       [16, 24, 25, 35],
       [48, 30,  8, 42]])

In [28]:
arr1 / arr2

array([[3.        , 1.        , 2.        , 0.75      ],
       [0.25      , 1.5       , 1.        , 1.4       ],
       [0.75      , 0.83333333, 8.        , 0.85714286]])

In [29]:
arr1 @ arr2  # matrix multiplication

ValueError: ignored

We are getting error because the number of columns in the first matrix must be equal to the number of rows in the second matrix. Here it is not the case

In [30]:
arr1 - arr2

array([[ 4,  0,  2, -1],
       [-6,  2,  0,  2],
       [-2, -1,  7, -1]])

In [31]:
arr1 ** arr2

array([[      36, 16777216,       16,       81],
       [     256,     1296,     3125,    16807],
       [ 1679616,    15625,        8,   279936]])

In [32]:
~arr1

array([[-7, -9, -5, -4],
       [-3, -7, -6, -8],
       [-7, -6, -9, -7]])

In [33]:
arr1 > arr2

array([[ True, False,  True, False],
       [False,  True, False,  True],
       [False, False,  True, False]])

In [34]:
arr1 > 4

array([[ True,  True, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
arr1[arr1 > 4]

array([6, 8, 6, 5, 7, 6, 5, 8, 6])

### Numpy -> String Operation

In [36]:
arr = np.array(["abhay", "magar"])
arr

array(['abhay', 'magar'], dtype='<U5')

In [37]:
np.char.upper(arr)

array(['ABHAY', 'MAGAR'], dtype='<U5')

In [38]:
np.char.capitalize(arr)

array(['Abhay', 'Magar'], dtype='<U5')

In [39]:
np.char.title(arr)

array(['Abhay', 'Magar'], dtype='<U5')

### Numpy -> Mathematical Functions

In [40]:
arr1

array([[6, 8, 4, 3],
       [2, 6, 5, 7],
       [6, 5, 8, 6]])

In [41]:
np.sin(arr1)

array([[-0.2794155 ,  0.98935825, -0.7568025 ,  0.14112001],
       [ 0.90929743, -0.2794155 , -0.95892427,  0.6569866 ],
       [-0.2794155 , -0.95892427,  0.98935825, -0.2794155 ]])

In [42]:
np.cos(arr1)

array([[ 0.96017029, -0.14550003, -0.65364362, -0.9899925 ],
       [-0.41614684,  0.96017029,  0.28366219,  0.75390225],
       [ 0.96017029,  0.28366219, -0.14550003,  0.96017029]])

In [43]:
np.tan(arr1)

array([[-0.29100619, -6.79971146,  1.15782128, -0.14254654],
       [-2.18503986, -0.29100619, -3.38051501,  0.87144798],
       [-0.29100619, -3.38051501, -6.79971146, -0.29100619]])

In [44]:
np.log(arr1)

array([[1.79175947, 2.07944154, 1.38629436, 1.09861229],
       [0.69314718, 1.79175947, 1.60943791, 1.94591015],
       [1.79175947, 1.60943791, 2.07944154, 1.79175947]])

In [46]:
np.log10(arr1)

array([[0.77815125, 0.90308999, 0.60205999, 0.47712125],
       [0.30103   , 0.77815125, 0.69897   , 0.84509804],
       [0.77815125, 0.69897   , 0.90308999, 0.77815125]])

In [47]:
np.log2(arr1)

array([[2.5849625 , 3.        , 2.        , 1.5849625 ],
       [1.        , 2.5849625 , 2.32192809, 2.80735492],
       [2.5849625 , 2.32192809, 3.        , 2.5849625 ]])

In [48]:
np.exp(arr1) # Exponent

array([[ 403.42879349, 2980.95798704,   54.59815003,   20.08553692],
       [   7.3890561 ,  403.42879349,  148.4131591 , 1096.63315843],
       [ 403.42879349,  148.4131591 , 2980.95798704,  403.42879349]])

In [50]:
np.power(arr1, 2)   # Power of 2

array([[36, 64, 16,  9],
       [ 4, 36, 25, 49],
       [36, 25, 64, 36]])

In [51]:
np.mean(arr1)

5.5

In [52]:
np.median(arr1)

6.0

In [53]:
np.mode(arr1)

AttributeError: ignored

In [54]:
np.std(arr1)

1.7559422921421233

In [55]:
np.var(arr1)

3.0833333333333335

In [56]:
np.min(arr1)

2

In [57]:
np.max(arr1)

8

### Numpy -> arithmetic Operations

In [61]:
arr1

array([[6, 8, 4, 3],
       [2, 6, 5, 7],
       [6, 5, 8, 6]])

In [62]:
arr2

array([[2, 8, 2, 4],
       [8, 4, 5, 5],
       [8, 6, 1, 7]])

In [63]:
arr1 - arr2

array([[ 4,  0,  2, -1],
       [-6,  2,  0,  2],
       [-2, -1,  7, -1]])

In [64]:
np.subtract(arr1, arr2)

array([[ 4,  0,  2, -1],
       [-6,  2,  0,  2],
       [-2, -1,  7, -1]])

In [65]:
np.multiply(arr1, arr2)

array([[12, 64,  8, 12],
       [16, 24, 25, 35],
       [48, 30,  8, 42]])

In [67]:
np.mod(arr1, arr2) # Gives remainder

array([[0, 0, 0, 3],
       [2, 2, 0, 2],
       [6, 5, 0, 6]])

In [68]:
np.power(arr1, arr2)

array([[      36, 16777216,       16,       81],
       [     256,     1296,     3125,    16807],
       [ 1679616,    15625,        8,   279936]])

In [69]:
np.sqrt(arr1)

array([[2.44948974, 2.82842712, 2.        , 1.73205081],
       [1.41421356, 2.44948974, 2.23606798, 2.64575131],
       [2.44948974, 2.23606798, 2.82842712, 2.44948974]])