In [34]:
import numpy as np

### Sort, Search an Counting Functions

In [35]:
arr = np.array([5,2,8,6,3])
arr

array([5, 2, 8, 6, 3])

In [36]:
arr.sort()
arr

array([2, 3, 5, 6, 8])

In [37]:
arr

array([2, 3, 5, 6, 8])

In [38]:
arr = np.array([5,2,8,6,3])
np.sort(arr)

array([2, 3, 5, 6, 8])

In [39]:
np.searchsorted(arr,6)   #Find indices where elements should be inserted to maintain order.

2

In [40]:
arr2 = np.array([1,2,3,4,6,7])

In [41]:
np.searchsorted(arr2, 5)

4

This means "5" should be added at "4"th index to maintain the order of sorting of arr2

In [47]:
arr1 = np.array([0,1,4,2,3,6,4,0,10])
arr1

array([ 0,  1,  4,  2,  3,  6,  4,  0, 10])

In [48]:
np.count_nonzero(arr1)

7

In [49]:
np.where(arr1 > 0)   # 7 numbers are greater than zero

(array([1, 2, 3, 4, 5, 6, 8]),)

In [50]:
np.extract(arr1 > 2, arr1)  # extract data from arr1 depending upon condn given

array([ 4,  3,  6,  4, 10])

In [51]:
np.where(arr1 > 2)

(array([2, 4, 5, 6, 8]),)

### Numpy -> Byte Swapping

In [52]:
arr1

array([ 0,  1,  4,  2,  3,  6,  4,  0, 10])

In [55]:
arr.byteswap()   # byte representation of data

array([360287970189639680, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

In [56]:
arr

array([5, 2, 8, 6, 3])

In [57]:
# TO make changes permanent

arr.byteswap(True)

array([360287970189639680, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

In [58]:
arr

array([360287970189639680, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

In [60]:
a = np.copy(arr1)  # Deep Copy
a

array([ 0,  1,  4,  2,  3,  6,  4,  0, 10])

In [66]:
b = arr.view()   # same as b = arr1
b

array([               234, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

In [67]:
b[0] = 234

In [68]:
b

array([               234, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

In [69]:
arr

array([               234, 144115188075855872, 576460752303423488,
       432345564227567616, 216172782113783808])

Hence It is a Shallow Copy. All the changes are reverted to original array also

In [71]:
a[0] = 4556

In [72]:
a

array([4556,    1,    4,    2,    3,    6,    4,    0,   10])

In [73]:
arr1

array([ 0,  1,  4,  2,  3,  6,  4,  0, 10])

Hence It is a DEEP Copy. All the changes are NOT reverted to original array. Both are independent

### Numpy -> Matrix Library

In [74]:
import numpy.matlib as nm

In [75]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [76]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [77]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [78]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [80]:
nm.eye(4)   # Identity Matrix

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

### Numpy - Linear ALgebra

In [81]:
arr1

array([ 0,  1,  4,  2,  3,  6,  4,  0, 10])

In [95]:
arr1 = np.random.randint([[2,3], [4,5]])
arr1

array([[1, 0],
       [0, 4]])

In [96]:
arr2 = np.random.randint([[5,3], [2,5]])
arr2

array([[4, 2],
       [1, 2]])

In [97]:
np.dot(arr1, arr2)

array([[4, 2],
       [4, 8]])

In [98]:
arr1 @ arr2

array([[4, 2],
       [4, 8]])

### DOT PRODUCT IS NOTHING BUT MATRIX MULTIPLICATION